spring:
  profiles:
    include: secret
    active: develop

management:
  endpoints:
    web:
      exposure:
        include: prometheus  # Prometheus 엔드포인트 노출
  metrics:
    export:
      prometheus:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: develop
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

cloud:
  aws:
    s3:
      bucket: boardcollie.com
    credentials:
      access-key: AKIA4C5LB37747GR4BOE
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false