spring:
  profiles:
    include: secret
    active: develop

management:
  endpoints:
    web:
      exposure:
        include: prometheus  # Prometheus 엔드포인트 노출
  metrics:
    export:
      prometheus:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: develop
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
