spring:
  profiles:
    include: secret
    active: develop

management:
  endpoints:
    web:
      exposure:
        include: prometheus  # Prometheus 엔드포인트 노출
  metrics:
    export:
      prometheus:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: develop
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver